// Generated by wasm-pack during `npm run wasm:build:*`.
import initWasm, {
  Sim,
  wasm_loaded_message,
} from "../../sim-wasm/pkg/sim_wasm.js";

export class WasmSimClient {
  private readonly sim: Sim;
  private readonly wasmMemory: WebAssembly.Memory;
  private positionsView: Float32Array;
  private memoryBuffer: ArrayBuffer;
  private readonly pointer: number;
  private readonly length: number;

  constructor(
    count: number,
    seed: number,
    width: number,
    height: number,
    wasmMemory: WebAssembly.Memory,
  ) {
    this.sim = new Sim(count, seed, width, height);
    this.wasmMemory = wasmMemory;
    this.pointer = this.sim.render_xy_ptr();
    this.length = this.sim.render_xy_len();
    this.memoryBuffer = wasmMemory.buffer;
    this.positionsView = new Float32Array(
      this.memoryBuffer,
      this.pointer,
      this.length,
    );
  }

  step(dt: number): void {
    this.sim.step(dt);
    this.refreshViewIfMemoryChanged();
  }

  setBounds(width: number, height: number): void {
    this.sim.set_bounds(width, height);
  }

  getCount(): number {
    return this.sim.count();
  }

  getPositions(): Float32Array {
    this.refreshViewIfMemoryChanged();
    return this.positionsView;
  }

  getPointer(): number {
    return this.pointer;
  }

  private refreshViewIfMemoryChanged(): void {
    if (this.memoryBuffer === this.wasmMemory.buffer) {
      return;
    }

    this.memoryBuffer = this.wasmMemory.buffer;
    this.positionsView = new Float32Array(
      this.memoryBuffer,
      this.pointer,
      this.length,
    );
  }
}

export async function initWasmModule(): Promise<WasmSimClient> {
  const wasm = await initWasm();
  console.log(wasm_loaded_message());

  const sim = new WasmSimClient(4_000, 12_345, 1.0, 1.0, wasm.memory);
  console.log("Sim ready", {
    count: sim.getCount(),
    ptr: sim.getPointer(),
  });

  return sim;
}
