// Generated by wasm-pack during `npm run wasm:build:*`.
import initWasm, { wasm_loaded_message } from "../../sim-wasm/pkg/sim_wasm.js";

export async function initWasmModule(): Promise<void> {
  await initWasm();
  console.log(wasm_loaded_message());
}
